baseURL = "https://example.com"

languageCode = "en-us"
DefaultContentLanguage = "en"
title = "Hints and tips"
theme = "learn"

hasCJKLanguage = false
metaDataFormat = "yaml"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir= false
enableMissingTranslationPlaceholders = false

[params]
    # Prefix URL to edit current page. Will display an "Edit this page" button on top right hand corner of every page.
    # Useful to give opportunity to people to create merge request for your doc.
    # See the config.toml file from this documentation site to have an example.
    editURL = "https://github.com/tim-barnes/hints/edit/master/content/"
    # Author of the site, will be used in meta information
    author = "Tim Barnes"
    # Description of the site, will be used in meta information
    description = "This is a collection of random notes captured over a long career in software engineering. Most are fairly up to date. Some, like general quality tips, are invariant. Others are thoughts on trends in software development, either current or past."
    # Shows a checkmark for visited pages on the menu
    showVisitedLinks = false
    # Disable search function. It will hide search bar
    disableSearch = false
    # Javascript and CSS cache are automatically busted when new version of site is generated.
    # Set this to true to disable this behavior (some proxies don't handle well this optimization)
    disableAssetsBusting = false
    # Set this to true to disable copy-to-clipboard button for inline code.
    disableInlineCopyToClipBoard = false
    # A title for shortcuts in menu is set by default. Set this to true to disable it.
    disableShortcutsTitle = false
    # When using mulitlingual website, disable the switch language button.
    disableLanguageSwitchingButton = false
    # Hide breadcrumbs in the header and only show the current page title
    disableBreadcrumb = false
    # Hide Next and Previous page buttons normally displayed full height beside content
    disableNextPrev = false
    # Order sections in menu by "weight" or "title". Default to "weight"
    ordersectionsby = "weight"
    # Change default color scheme with a variant one. Can be "red", "blue", "green".
    themeVariant = "blue"
    # Provide a list of custom css files to load relative from the `static/` folder in the site root.
    custom_css = []

[outputs]
home = [ "HTML", "RSS", "JSON"]

# Global menu section
[[menu.shortcuts]]
name = "<i class='fas fa-tags'></i> Tags"
url = "/tags"
weight = 1

[[menu.shortcuts]]
name = "<i class='fab fa-github'></i> Github"
url = "https://github.com/tim-barnes"
weight = 20

[[menu.shortcuts]]
name = "<i class='fab fa-linkedin'></i> LinkedIn"
url = "https://www.linkedin.com/in/tim-barnes-63b58624/"
weight = 50


[[menu.shortcuts]]
name = "<i class='fas fa-file-alt'></i> License CC-BY-4.0"
url = "https://github.com/tim-barnes/hints/blob/master/LICENSE"
weight = 100



# Markup configure section
# See https://gohugo.io/getting-started/configuration-markup/
[markup]
    defaultMarkdownHandler = "goldmark"
    [markup.goldmark.renderer]
        unsafe= true
    [markup.tableOfContents]
        startLevel = 2
        endLevel = 4
        ordered = false

